CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    login varchar(255),
    email varchar(255),
    birthday date
);

CREATE TABLE IF NOT EXISTS friends (
    user1_id INTEGER REFERENCES users(user_id),
    user2_id INTEGER REFERENCES users(user_id),
    is_friend boolean,
    PRIMARY KEY (user1_id, user2_id)
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id integer PRIMARY KEY,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa (
    mpa_id integer PRIMARY KEY,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar (255) NOT NULL,
    description varchar (199),
    release_date date,
    duration integer,
    genre_id integer REFERENCES genre(genre_id),
    mpa_id integer REFERENCES mpa(mpa_id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id integer REFERENCES films(film_id),
    user_id integer REFERENCES users(user_id)
);


